resolver: lts-21.25

# Put documentation into an easily accessible directory.
build:
    haddock-arguments:
        haddock-args:
        - "--odir=./haddocks"

extra-deps:
    # temp additions for forward compatibility with text-builder new API
    - text-builder-1.0.0.4@sha256:19bc28b9ff0eed90b8154be50816bae255586e7c5533fddd2ce49b47c498d509,4941
    - text-builder-core-0.1.1.1@sha256:402fdf2f2695950643fea299719c3dccc81c797d94bbcaa7d1cbf182e9937afa,2844
